export default {
  webb: {
    id: `webb`,
    date: `2016-08-03T04:00:00.000Z`,
    title: `A Letter of Elizabeth Webb`,
    friend: `Elizabeth Webb`,
    friendSort: `Webb, Elizabeth`,
    reader: `Jason R. Henderson`,
    artwork: `https://flp-assets.nyc3.digitaloceanspaces.com/en/elizabeth-webb/letter/updated/Letter_of_Elizabeth_Webb--updated--audio.png`,
    description: `Elizabeth Webb (1663-1726) was an early minister in the Society of Friends who travelled extensively in her service for the gospel. In the year 1712, while ministering in London, she became acquainted with Anthony William Boehm, then chaplain to Prince George of Denmark. At some point following their initial interview, Elizabeth Webb felt constrained in the love of God to write to Boehm and present him with the deeply instructive letter contained in this booklet, giving something of a summary of her spiritual pilgrimage.`,
    shortDescription: `A letter from Elizabeth Webb written to Anthony William Boehm (chaplain to Prince George of Denmark), in which she describes her own spiritual journey, and her experience of the Lord’s judgments and mercies as she gave up resolutely to follow Him.`,
    parts: [
      {
        audioId: `a52eb875-8a1a-4f2f-b1b4-650eb3af1126--updated`,
        index: 0,
        title: `The Life of Elizabeth Webb`,
        duration: 2843.5,
        size: 26854763,
        sizeLq: 14290634,
        url: `https://flp-assets.nyc3.digitaloceanspaces.com/en/elizabeth-webb/letter/updated/Letter_of_Elizabeth_Webb.mp3`,
        urlLq: `https://flp-assets.nyc3.digitaloceanspaces.com/en/elizabeth-webb/letter/updated/Letter_of_Elizabeth_Webb--lq.mp3`,
      },
    ],
  },
  penington: {
    id: `penington`,
    date: `2015-12-04T05:00:00.000Z`,
    title: `The Writings of Isaac Penington -- Volume 1`,
    friend: `Isaac Penington`,
    friendSort: `Penington, Isaac`,
    reader: `Jason R. Henderson`,
    artwork: `https://flp-assets.nyc3.digitaloceanspaces.com/en/isaac-penington/writings-volume-1/updated/Writings_of_Isaac_Penington_vol_1--updated--audio.png`,
    description: `Isaac Penington (1616-1679) was the son of a prominent English politician, and the father-in-law of William Penn, founder of Pennsylvania. Though born into a family of wealth and reputation, Penington’s heart was set upon things above from his earliest days. Even as a child, he recognized that the religion of his day stood in the will and understanding of man, in outward practices, duties, and scriptural truths that were professed but not truly possessed. Isaac Penington longed for more. Motivated by an insatiable hunger for truth, he sought the Lord with all his heart and discovered a Christianity that stood in, and flowed out from, the light and life of Jesus Christ reigning in the inner man.`,
    shortDescription: `Volume One of The Writings of Isaac Penington, a conscientiously abridged, and slightly modernized and annotated edition of his four volume complete works (which can also be found on this site.)`,
    parts: [
      {
        audioId: `c248c2e7-947b-4629-8296-0cdff67a6d99--updated`,
        index: 0,
        title: `Chapter 1`,
        duration: 2892.55,
        size: 29616809,
        sizeLq: 14529636,
        url: `https://flp-assets.nyc3.digitaloceanspaces.com/en/isaac-penington/writings-volume-1/updated/Writings_of_Isaac_Penington_vol_1--pt1.mp3`,
        urlLq: `https://flp-assets.nyc3.digitaloceanspaces.com/en/isaac-penington/writings-volume-1/updated/Writings_of_Isaac_Penington_vol_1--pt1--lq.mp3`,
      },
      {
        audioId: `c248c2e7-947b-4629-8296-0cdff67a6d99--updated`,
        index: 1,
        title: `Chapter 2`,
        duration: 4377.85,
        size: 41822426,
        sizeLq: 21956118,
        url: `https://flp-assets.nyc3.digitaloceanspaces.com/en/isaac-penington/writings-volume-1/updated/Writings_of_Isaac_Penington_vol_1--pt2.mp3`,
        urlLq: `https://flp-assets.nyc3.digitaloceanspaces.com/en/isaac-penington/writings-volume-1/updated/Writings_of_Isaac_Penington_vol_1--pt2--lq.mp3`,
      },
      {
        audioId: `c248c2e7-947b-4629-8296-0cdff67a6d99--updated`,
        index: 2,
        title: `Chapter 3`,
        duration: 2269.96,
        size: 22042711,
        sizeLq: 11416624,
        url: `https://flp-assets.nyc3.digitaloceanspaces.com/en/isaac-penington/writings-volume-1/updated/Writings_of_Isaac_Penington_vol_1--pt3.mp3`,
        urlLq: `https://flp-assets.nyc3.digitaloceanspaces.com/en/isaac-penington/writings-volume-1/updated/Writings_of_Isaac_Penington_vol_1--pt3--lq.mp3`,
      },
      {
        audioId: `c248c2e7-947b-4629-8296-0cdff67a6d99--updated`,
        index: 3,
        title: `Chapter 4`,
        duration: 3474.55,
        size: 35346288,
        sizeLq: 17439677,
        url: `https://flp-assets.nyc3.digitaloceanspaces.com/en/isaac-penington/writings-volume-1/updated/Writings_of_Isaac_Penington_vol_1--pt4.mp3`,
        urlLq: `https://flp-assets.nyc3.digitaloceanspaces.com/en/isaac-penington/writings-volume-1/updated/Writings_of_Isaac_Penington_vol_1--pt4--lq.mp3`,
      },
      {
        audioId: `c248c2e7-947b-4629-8296-0cdff67a6d99--updated`,
        index: 4,
        title: `Chapter 5`,
        duration: 3301.65,
        size: 31674351,
        sizeLq: 16575154,
        url: `https://flp-assets.nyc3.digitaloceanspaces.com/en/isaac-penington/writings-volume-1/updated/Writings_of_Isaac_Penington_vol_1--pt5.mp3`,
        urlLq: `https://flp-assets.nyc3.digitaloceanspaces.com/en/isaac-penington/writings-volume-1/updated/Writings_of_Isaac_Penington_vol_1--pt5--lq.mp3`,
      },
      {
        audioId: `c248c2e7-947b-4629-8296-0cdff67a6d99--updated`,
        index: 5,
        title: `Chapter 6`,
        duration: 1673.88,
        size: 19336319,
        sizeLq: 8436314,
        url: `https://flp-assets.nyc3.digitaloceanspaces.com/en/isaac-penington/writings-volume-1/updated/Writings_of_Isaac_Penington_vol_1--pt6.mp3`,
        urlLq: `https://flp-assets.nyc3.digitaloceanspaces.com/en/isaac-penington/writings-volume-1/updated/Writings_of_Isaac_Penington_vol_1--pt6--lq.mp3`,
      },
      {
        audioId: `c248c2e7-947b-4629-8296-0cdff67a6d99--updated`,
        index: 6,
        title: `Chapter 7`,
        duration: 1204.57,
        size: 11846093,
        sizeLq: 6089734,
        url: `https://flp-assets.nyc3.digitaloceanspaces.com/en/isaac-penington/writings-volume-1/updated/Writings_of_Isaac_Penington_vol_1--pt7.mp3`,
        urlLq: `https://flp-assets.nyc3.digitaloceanspaces.com/en/isaac-penington/writings-volume-1/updated/Writings_of_Isaac_Penington_vol_1--pt7--lq.mp3`,
      },
      {
        audioId: `c248c2e7-947b-4629-8296-0cdff67a6d99--updated`,
        index: 7,
        title: `Chapter 8`,
        duration: 2134.69,
        size: 21203165,
        sizeLq: 10740314,
        url: `https://flp-assets.nyc3.digitaloceanspaces.com/en/isaac-penington/writings-volume-1/updated/Writings_of_Isaac_Penington_vol_1--pt8.mp3`,
        urlLq: `https://flp-assets.nyc3.digitaloceanspaces.com/en/isaac-penington/writings-volume-1/updated/Writings_of_Isaac_Penington_vol_1--pt8--lq.mp3`,
      },
      {
        audioId: `c248c2e7-947b-4629-8296-0cdff67a6d99--updated`,
        index: 8,
        title: `Chapter 9`,
        duration: 3828.22,
        size: 34071061,
        sizeLq: 19207879,
        url: `https://flp-assets.nyc3.digitaloceanspaces.com/en/isaac-penington/writings-volume-1/updated/Writings_of_Isaac_Penington_vol_1--pt9.mp3`,
        urlLq: `https://flp-assets.nyc3.digitaloceanspaces.com/en/isaac-penington/writings-volume-1/updated/Writings_of_Isaac_Penington_vol_1--pt9--lq.mp3`,
      },
      {
        audioId: `c248c2e7-947b-4629-8296-0cdff67a6d99--updated`,
        index: 9,
        title: `Chapter 10`,
        duration: 2292.08,
        size: 19958098,
        sizeLq: 11527231,
        url: `https://flp-assets.nyc3.digitaloceanspaces.com/en/isaac-penington/writings-volume-1/updated/Writings_of_Isaac_Penington_vol_1--pt10.mp3`,
        urlLq: `https://flp-assets.nyc3.digitaloceanspaces.com/en/isaac-penington/writings-volume-1/updated/Writings_of_Isaac_Penington_vol_1--pt10--lq.mp3`,
      },
      {
        audioId: `c248c2e7-947b-4629-8296-0cdff67a6d99--updated`,
        index: 10,
        title: `Chapter 11`,
        duration: 2554.25,
        size: 21779167,
        sizeLq: 12838056,
        url: `https://flp-assets.nyc3.digitaloceanspaces.com/en/isaac-penington/writings-volume-1/updated/Writings_of_Isaac_Penington_vol_1--pt11.mp3`,
        urlLq: `https://flp-assets.nyc3.digitaloceanspaces.com/en/isaac-penington/writings-volume-1/updated/Writings_of_Isaac_Penington_vol_1--pt11--lq.mp3`,
      },
      {
        audioId: `c248c2e7-947b-4629-8296-0cdff67a6d99--updated`,
        index: 11,
        title: `Chapter 12`,
        duration: 4525.32,
        size: 40025780,
        sizeLq: 22693403,
        url: `https://flp-assets.nyc3.digitaloceanspaces.com/en/isaac-penington/writings-volume-1/updated/Writings_of_Isaac_Penington_vol_1--pt12.mp3`,
        urlLq: `https://flp-assets.nyc3.digitaloceanspaces.com/en/isaac-penington/writings-volume-1/updated/Writings_of_Isaac_Penington_vol_1--pt12--lq.mp3`,
      },
      {
        audioId: `c248c2e7-947b-4629-8296-0cdff67a6d99--updated`,
        index: 12,
        title: `Chapter 13`,
        duration: 3034.6,
        size: 26475602,
        sizeLq: 15239884,
        url: `https://flp-assets.nyc3.digitaloceanspaces.com/en/isaac-penington/writings-volume-1/updated/Writings_of_Isaac_Penington_vol_1--pt13.mp3`,
        urlLq: `https://flp-assets.nyc3.digitaloceanspaces.com/en/isaac-penington/writings-volume-1/updated/Writings_of_Isaac_Penington_vol_1--pt13--lq.mp3`,
      },
      {
        audioId: `c248c2e7-947b-4629-8296-0cdff67a6d99--updated`,
        index: 13,
        title: `Chapter 14`,
        duration: 3038.82,
        size: 27130906,
        sizeLq: 15260913,
        url: `https://flp-assets.nyc3.digitaloceanspaces.com/en/isaac-penington/writings-volume-1/updated/Writings_of_Isaac_Penington_vol_1--pt14.mp3`,
        urlLq: `https://flp-assets.nyc3.digitaloceanspaces.com/en/isaac-penington/writings-volume-1/updated/Writings_of_Isaac_Penington_vol_1--pt14--lq.mp3`,
      },
      {
        audioId: `c248c2e7-947b-4629-8296-0cdff67a6d99--updated`,
        index: 14,
        title: `Chapter 15`,
        duration: 1538.7,
        size: 13606683,
        sizeLq: 7760374,
        url: `https://flp-assets.nyc3.digitaloceanspaces.com/en/isaac-penington/writings-volume-1/updated/Writings_of_Isaac_Penington_vol_1--pt15.mp3`,
        urlLq: `https://flp-assets.nyc3.digitaloceanspaces.com/en/isaac-penington/writings-volume-1/updated/Writings_of_Isaac_Penington_vol_1--pt15--lq.mp3`,
      },
      {
        audioId: `c248c2e7-947b-4629-8296-0cdff67a6d99--updated`,
        index: 15,
        title: `Chapter 16a`,
        duration: 2498.58,
        size: 21138992,
        sizeLq: 12559526,
        url: `https://flp-assets.nyc3.digitaloceanspaces.com/en/isaac-penington/writings-volume-1/updated/Writings_of_Isaac_Penington_vol_1--pt16.mp3`,
        urlLq: `https://flp-assets.nyc3.digitaloceanspaces.com/en/isaac-penington/writings-volume-1/updated/Writings_of_Isaac_Penington_vol_1--pt16--lq.mp3`,
      },
      {
        audioId: `c248c2e7-947b-4629-8296-0cdff67a6d99--updated`,
        index: 16,
        title: `Chapter 16b`,
        duration: 3053.63,
        size: 25860418,
        sizeLq: 15334775,
        url: `https://flp-assets.nyc3.digitaloceanspaces.com/en/isaac-penington/writings-volume-1/updated/Writings_of_Isaac_Penington_vol_1--pt17.mp3`,
        urlLq: `https://flp-assets.nyc3.digitaloceanspaces.com/en/isaac-penington/writings-volume-1/updated/Writings_of_Isaac_Penington_vol_1--pt17--lq.mp3`,
      },
      {
        audioId: `c248c2e7-947b-4629-8296-0cdff67a6d99--updated`,
        index: 17,
        title: `Chapter 16c`,
        duration: 3097.91,
        size: 25829968,
        sizeLq: 15556163,
        url: `https://flp-assets.nyc3.digitaloceanspaces.com/en/isaac-penington/writings-volume-1/updated/Writings_of_Isaac_Penington_vol_1--pt18.mp3`,
        urlLq: `https://flp-assets.nyc3.digitaloceanspaces.com/en/isaac-penington/writings-volume-1/updated/Writings_of_Isaac_Penington_vol_1--pt18--lq.mp3`,
      },
      {
        audioId: `c248c2e7-947b-4629-8296-0cdff67a6d99--updated`,
        index: 18,
        title: `Chapter 16d`,
        duration: 2503.61,
        size: 19766204,
        sizeLq: 12584734,
        url: `https://flp-assets.nyc3.digitaloceanspaces.com/en/isaac-penington/writings-volume-1/updated/Writings_of_Isaac_Penington_vol_1--pt19.mp3`,
        urlLq: `https://flp-assets.nyc3.digitaloceanspaces.com/en/isaac-penington/writings-volume-1/updated/Writings_of_Isaac_Penington_vol_1--pt19--lq.mp3`,
      },
    ],
  },
};
